name: WWW-Google-News-TW
version: 0.09
abstract: Access to Google's Taiwan News Service
author: Cheng-Lung Sung <clsung@dragon2.net>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Test::More: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
